title: "MinionAH Status"
home: "/"
logo: "/logo.png"
github:
  owner: "DarthGigi"
  repo: "MinionAH-Status"
metaTags:
  description: "MinionAH Status is a status page for MinionAH, showing the current status of MinionAH services. It also provides a history of incidents and their resolutions."
  keywords: "MinionAH status page, MinionAH monitoring, MinionAH outage tracking, Real-time MinionAH status updates"
  og:description: "MinionAH Status is a status page for MinionAH, showing the current status of MinionAH services. It also provides a history of incidents and their resolutions."
  og:image: "https://minionah.com/assets/images/ogBanner.png"
  og:title: "MinionAH Status"
  og:type: "website"
  og:site_name: "MinionAH"
  twitter:card: "summary_large_image"
  twitter:site: "@idarthgigi"
  twitter:creator: "@idarthgigi"
  twitter:image: "https://minionah.com/assets/images/ogBanner.png"
  twitter:title: "MinionAH Status"
  twitter:description: "MinionAH Status is a status page for MinionAH, showing the current status of MinionAH services. It also provides a history of incidents and their resolutions."
nav:
  - name: "OG"
    url: "https://og.minionah.com"
  - name: "Newsroom"
    url: "https://newsroom.minionah.com"
  - name: "MinionAH"
    url: "https://minionah.com"
hero:
  title: "MinionAH"
  subtitle: "Current status"
